### PR TITLE
chore: ic-ref CI: Use ghc-8.8.4

### PR DESCRIPTION
**Pull request by nomeata**
to match what’s in nixpkgs-20.09

### CODE REVIEW

**Comment by nomeata** [comment]
It seems that Github is not picking up the changes to the workflow in this PR?

**Comment by ggreif** [comment]
Maybe due to the project migration (dfinity-lab -> dfinity)?

**Comment by nomeata** [comment]
No, none of the involved repos has moved. More likely a security feature of GitHub actions, given that this is running untrustworthy PRs.

**Comment by hansl** [comment]
@nomeata it's because it's on `pull_request_target` which means that it only run the target repo's workflow (base branch). Add a `pull_request` to it.

**Comment by hansl** [comment]
After line 7, add `pull_target:` (empty, same indentation as the one above). That will fix it and the proper way too.

**Comment by nomeata** [comment]
As expected, this does not work: As this is a PR from a forked repo, it doesn’t have access to the `secrets.IC_REF_TOKEN`:

```
2020-10-14T08:11:12.5538872Z ##[group]Run actions/checkout@v2
2020-10-14T08:11:12.5539305Z with:
2020-10-14T08:11:12.5539593Z   repository: dfinity-lab/ic-ref
2020-10-14T08:11:12.5539890Z   path: ic-ref
2020-10-14T08:11:12.5540136Z   ref: release-0.11
2020-10-14T08:11:12.5540403Z   ssh-strict: true
2020-10-14T08:11:12.5540893Z   persist-credentials: true
2020-10-14T08:11:12.5541244Z   clean: true
2020-10-14T08:11:12.5541516Z   fetch-depth: 1
2020-10-14T08:11:12.5541793Z   lfs: false
2020-10-14T08:11:12.5542066Z   submodules: false
2020-10-14T08:11:12.5542349Z ##[endgroup]
2020-10-14T08:11:12.6458923Z ##[error]Input required and not supplied: token
```

**Comment by nomeata** [comment]
I’ll leave this to you, either just merge, or create a PR from a branch within the `agent-rs` repo

**Comment by hansl** [comment]
Oh sorry, you did the right thing :). I didn't see you were using a fork...

**Comment by hansl** [comment]
I'll take care of it.

**Comment by hansl** [comment]
I'll take care of it. For the record when changing CI itself it's better to use a branch on the repo.

**Comment by nomeata** [comment]
> For the record when changing CI itself it's better to use a branch on the repo.

I somehow thought that’s discouraged? But I guess that’s a pragmatic exception from the rule then?

**Pull request closed without merging**
