### PR TITLE
feat: Hashtree path lookup

### PR DESCRIPTION
**Pull request by matthewhammer**
Extends #71 with additional code, for path lookup.

This completes item (b) from our response auth checklist.

### CODE REVIEW

**Review by ericswanson-dfinity — APPROVED** [review]

**Comment by ericswanson-dfinity** [comment]
@hansl this is blocking

**Comment by matthewhammer** [comment]
I hereby give @hansl permission to change this PR and #71 any way he wants so satisfy his desiderata for the repo.  I don't need to understand or agree, and I suspect that I will not.  : )

**Comment by matthewhammer** [comment]
Surprised this (still) isn't merged.

Is it not blocking @ericswanson-dfinity anymore?  (If it is still critical, are the comments above really that critical to address now, in this PR?)

**Comment by ericswanson-dfinity** [comment]
I

**Pull request closed without merging**
